language: php
sudo: required
dist: focal
group: edge

php:
  - 8.1

sudo: false

services:
  - mysql

before_script:
  - mysql -u root -e 'create database laravelroles;'
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - composer create-project --prefer-dist laravel/laravel laravelroles
  - cp .env.travis laravelroles/.env
  - cd laravelroles
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload
  - composer require jeremykenedy/laravel-roles
  - composer require laravel/ui
  - php artisan key:generate
  - php artisan vendor:publish --tag=laravelroles
  - php artisan ui vue --auth
  - composer dump-autoload
  - php artisan clear-compiled

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: vendor/bin/phpunit
